name: filebeat-host-elk

filebeat.inputs:
- type: log
  name: dev-operation-log
  paths:
    - /usr/share/filebeat/logs/operations.log
  json.message_key: log
  #json.keys_under_root: true
  #json.add_error_key: true


- type: log
  name: dev-application-log
  paths:
    - /usr/share/filebeat/logs/application.log
  json.message_key: log
  #json.keys_under_root: true
  #json.add_error_key: true
  
- type: log
  name: test-application-log
  paths:
    - /var/log/schoolsystem/test/application.log
  json.message_key: log
  #json.keys_under_root: true
  #json.add_error_key: true

- type: log
  name: test-operation-log
  paths:
    - /var/log/schoolsystem/test/operations.log
  json.message_key: log
  #json.keys_under_root: true
  #json.add_error_key: true

output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  username: elastic
  password: changeme


http:
  enabled: true
  host: 0.0.0.0
