name: filebeat-host-elk

# filebeat.modules:
# - module: nginx
#   access:
#     enabled: true
#     var.paths: ["/var/log/nginx/access.log"]

# filebeat.inputs:
# - type: log
#   name: dev-operation-log
#   paths:
#     - /var/log/operations.log
#   json.message_key: log

output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: elastic
  password: elk4565

http:
  enabled: true
  host: 0.0.0.0
