name: filebeat-host-elk

filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["/var/log/nginx/access.log*"]
    error:
      enabled: true
      var.paths: ["/var/log/nginx/error.log*"]

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      process_array: true
      max_depth: 1
      add_error_key: true
  - dissect:
      tokenizer: "%{nginx.access.remote_ip} %{ident} %{auth} [%{nginx.access.time_local}] \"%{http.request.method} %{uri} HTTP/%{http.version}\" %{nginx.access.response_status_code:int} %{nginx.access.body_bytes_sent:int} \"%{referrer}\" \"%{user_agent}\""
      field: "message"
      target_prefix: ""


output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: elastic
  password: changeme

http:
  enabled: true
  host: 0.0.0.0
