name: filebeat-host-elk

filebeat.inputs:
- type: log
  name: dev-operation-log
  paths:
    - /var/log/nginx/access.log
  json.message_key: log
  #json.keys_under_root: true
  #json.add_error_key: true

output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: elastic
  password: changeme

http:
  enabled: true
  host: 0.0.0.0
